language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-29
    - sys-img-armeabi-v7a-android-29

sudo: required

before_install:
  - yes | sdkmanager "platforms;android-29"
  
before_script:
    # Create and start emulator
    - echo no | android create avd --force -n test -t android-29 --abi armeabi-v7a -s "768x1280"
    - emulator -avd test -no-audio -no-window &
    - adb wait-for-device
    - adb shell input keyevent 82 &

script: ./gradlew :app:build :app:connectedDebugAndroidTest