/*
 * CryptoTracker REST Server API
 * CryptoTracker API leírása.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: oliwasi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.oliwasi.cryptotracker.model;

import java.util.Objects;
import java.util.HashMap;

/**
 * Dictionary of currency pairs. Key is the abbrevation of currencies i.e: USDC_BTC
 */
public class CurrencyPairList extends HashMap<String, CurrencyPair> {

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrencyPairList {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
